repos:
  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.38
    hooks:
      - id: pymarkdown
        exclude: |
          (?x)^(
            CODE-LICENSE\.md|
            DATA-LICENSE\.md|
            \.github/pull_request_template\.md
          )$

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.16.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
